pipeline:
  stages:
    - id: buildTestHostedLinuxStage_1
      name: Build and Test on Harness Cloud
      clone:
        enabled: true
      cache:
        enabled: true
      steps:
        - name: Dev_tranin1
          id: Dev_tranin1
          build:
            uses: gitCloneStep
            with:
              connector: Github_Connector_Training1
              repo_name: https://github.com/chaitanyarudraraju/Understanding_Harness
              build:
                target: Git Branch
                branch: master
              pr_merge_strategy: Source Branch
              depth: "50"
              lfs_enabled: false
              debug: false
              fetch_tags: false
              insecure: false
